server :
  servlet :
    context-path : /
  port : 8080


spring :
  datasource :
    url : jdbc:mysql://localhost:3306/oauth
    driver-class-name : com.mysql.cj.jdbc.Driver
    password : root
    username : root

  jpa :
    hibernate :
      ddl-auto : create-drop
  profiles :
    include : google
