server :
  servlet :
    context-path : /
  port : 8080


oauth:
  google:
    redirect_uri: http://localhost:8080/oauth/callback
    client_id: 61528740066-savt6auv1dqdqkcp6pdk7trt331g82rq.apps.googleusercontent.com
    secret: hkPHfzaZes8H1erMhOtZYtRr
    response_type: code
    scope: email
spring :
  datasource :
    url : jdbc:mysql://localhost:3306/oauth
    driver-class-name : com.mysql.cj.jdbc.Driver
    password : root
    username : root

  jpa :
    hibernate :
      ddl-auto : create-drop